# Starter pipeline

trigger:
- main

pool:
  #vmImage: ubuntu-latest
  name: Default

stages:
  - stage: BuildDev
    displayName: Stage Build for Dev
    jobs:
    - deployment: BuildMobileApp
      displayName: Build for Mobile App for Dev
      environment: development
      steps:
        - script: echo 'Building Mobile Application for Dev'
          displayName: Step Building Mobile App for Dev
        - script: echo 'Running Unit Test for Dev'
          displayName: Step Running Unit Test for Dev
    - deployment: BuildReactApp
      dependsOn: BuildMobileApp
      displayName: Build for React App for Dev
      environment: development
      steps:
        - script: echo 'building react app for dev'
          displayName: Step Building Mobile App for Dev
        - script: echo 'running unit test for Dev'
          displayName: Step running unit tet for dev
    - deployment: BuildNodeApp
      displayName: Build for Node App for Dev
      environment: development
      dependsOn:
      - BuildMobileApp
      - BuildReactApp
      steps:
        - script: echo 'Building Node App for DEv'
          displayName: step building node app for dev
        - script: echo 'Running Unit Test for Node App en Dev' 
          displayName: step running unit test for node app en dev
  
  - stage: BuildStaging
    displayName: Stage Build for Staging
    dependsOn: BuildDev     #This stage runs after BuildDev State
    condition: succeeded('BuildDev')
    jobs:
    - deployment: BuildMobileApp
      displayName: Build for Mobile App for Staging
      environment: Staging
      steps:
        - script: echo 'building mobile app for staging'
          displayName: Step Building Mobile App for staging
        - script: echo 'running unit test for staging'
          displayName: Step running unit tet for staging
    - deployment: BuildReactApp
      displayName: Build for React App for Staging
      environment: Staging
      dependsOn: BuildMobileApp
      steps:
        - script: echo 'building react app for staging'
          displayName: Step Building Reac App for staging
        - script: echo 'running unit test for staging'
          displayName: Step running unit tet for staging
    - deployment: BuildNodeApp
      displayName: Build for Node App for Staging
      environment: Staging
      dependsOn:
      - BuildMobileApp
      - BuildReactApp
      steps:
        - script: echo 'building node app for staging'
          displayName: Step Building Node App for staging
        - script: echo 'running unit test for staging'
          displayName: Step running unit tet for staging
  
  - stage: BuildPro
    displayName: Stage Build for Production
    dependsOn: 
    - BuildDev        #This stage run after BuildDev
    - BuildStaging    #This stage run after BuildStaging 
    condition: and(succeeded('BuildDev'),succeeded('BuildStaging'))
    jobs:
    - deployment: BuildMobileApp
      displayName: Build for Mobile App for Production
      environment: Production
      steps:
        - script: echo 'building mobile app for production'
          displayName: Step Building mobile App for production
        - script: echo 'running unit test for production'
          displayName: Step running unit tet for production
    - deployment: BuildReactApp
      displayName: Build for React App for Production
      environment: Production
      dependsOn: BuildMobileApp
      steps:
        - script: echo 'building react app for production'
          displayName: Step Building react App for production
        - script: echo 'running unit test for production'
          displayName: Step running unit tet for production
    - deployment: BuildNodeApp
      displayName: Build for Node App for Production
      environment: Production
      dependsOn:
      - BuildMobileApp
      - BuildReactApp
      steps:
        - script: echo 'building node app for production'
          displayName: Step Building node App for production
        - script: echo 'running unit test for production'
          displayName: Step running unit tet for production
